// Post
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const UPDATE_POSTS = 'UPDATE_POSTS';

// User
export const AUTH_START = 'AUTH_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Search
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const SEARCH_PROFILE_SUCCESS = 'SEARCH_PROFILE_SUCCESS';
export const CLEAR_SEARCH_STATE = 'CLEAR_SEARCH_STATE';

// Friend
// export const ADD_FRIEND = 'ADD_FRIEND';
// export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
